import { jsPDF } from 'jspdf';
import { Prescription, PharmacyOrder, Medicine } from '../types';

export const generatePrescriptionPDF = (prescription: Prescription) => {
  const doc = new jsPDF();
  const lineHeight = 10;
  let y = 20;

  // Header
  doc.setFontSize(22);
  doc.setTextColor(14, 165, 233); // Brand color
  doc.text("VisionCare Centre", 105, y, { align: "center" });
  y += lineHeight;
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("123 Eye Avenue, Medical District, NY 10001", 105, y, { align: "center" });
  doc.text("Phone: (555) 123-4567 | Email: contact@visioncare.com", 105, y + 5, { align: "center" });
  y += 20;

  doc.setLineWidth(0.5);
  doc.setDrawColor(200);
  doc.line(10, y, 200, y);
  y += 10;

  // Patient Info
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Medical Prescription", 10, y);
  y += lineHeight;

  doc.setFontSize(12);
  doc.text(`Patient Name: ${prescription.patientName}`, 10, y);
  doc.text(`Date: ${new Date(prescription.date).toLocaleDateString()}`, 140, y);
  y += lineHeight;
  doc.text(`Diagnosis: ${prescription.diagnosis}`, 10, y);
  y += 15;

  // Medicines Table Header
  doc.setFillColor(240, 249, 255);
  doc.rect(10, y - 6, 190, 8, 'F');
  doc.setFont("helvetica", "bold");
  doc.text("Medicine", 12, y);
  doc.text("Dosage", 80, y);
  doc.text("Frequency", 120, y);
  doc.text("Duration", 170, y);
  doc.setFont("helvetica", "normal");
  y += lineHeight;

  // Medicines List
  prescription.medicines.forEach((med: Medicine) => {
    doc.text(med.name, 12, y);
    doc.text(med.dosage, 80, y);
    doc.text(med.frequency, 120, y);
    doc.text(med.duration, 170, y);
    y += lineHeight;
  });

  y += 10;
  
  // Instructions
  if (prescription.instructions) {
    doc.setFont("helvetica", "bold");
    doc.text("Instructions:", 10, y);
    doc.setFont("helvetica", "normal");
    y += 7;
    const splitInstructions = doc.splitTextToSize(prescription.instructions, 180);
    doc.text(splitInstructions, 10, y);
    y += (splitInstructions.length * 7) + 20;
  } else {
      y += 20;
  }

  // Footer
  doc.line(10, y, 80, y);
  doc.text(`Dr. ${prescription.doctorName}`, 10, y + 5);
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Electronically Generated by VisionCare System", 105, 280, { align: "center" });

  doc.save(`Prescription_${prescription.patientName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};

export const generateBillPDF = (order: PharmacyOrder, medicines: Medicine[]) => {
    const doc = new jsPDF();
    const lineHeight = 10;
    let y = 20;
  
    // Header
    doc.setFontSize(22);
    doc.setTextColor(14, 165, 233);
    doc.text("VisionCare Pharmacy", 105, y, { align: "center" });
    y += lineHeight;
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Receipt / Invoice", 105, y, { align: "center" });
    y += 20;
  
    doc.line(10, y, 200, y);
    y += 10;
  
    // Details
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Bill To: ${order.patientName}`, 10, y);
    doc.text(`Order #: ${order.id.substring(0, 8).toUpperCase()}`, 140, y);
    y += lineHeight;
    doc.text(`Prescribed By: Dr. ${order.doctorName}`, 10, y);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 140, y);
    y += 20;
  
    // Items
    doc.setFillColor(240, 249, 255);
    doc.rect(10, y - 6, 190, 8, 'F');
    doc.setFont("helvetica", "bold");
    doc.text("Description", 12, y);
    doc.text("Qty/Duration", 140, y);
    doc.setFont("helvetica", "normal");
    y += lineHeight;
  
    medicines.forEach((med) => {
      doc.text(med.name, 12, y);
      doc.text(med.duration, 140, y);
      y += lineHeight;
    });
  
    y += 10;
    doc.line(10, y, 200, y);
    y += 10;
  
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(`Total Amount: $${order.totalCost.toFixed(2)}`, 140, y);
  
    doc.save(`Bill_${order.patientName.replace(/\s+/g, '_')}.pdf`);
  };
